apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a-lt2g9xh-go
  janus-idp.io/tekton: a-lt2g9xh-go
  backstage.io/kubernetes-id: a-lt2g9xh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a-lt2g9xh-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
